#!/usr/bin/env bash 
# Script for transferring a file from our client to a server using SCP
# Assigning parameters to variables
# Check if correct number of arguments are provided

if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE SERVER_IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Transfer file using SCP
scp -o StrictHostKeyChecking=no -i "${ssh_key}" "${file_path}" "${username}@${server_ip}:~/"

# Configures Nginx server for redirection and default error pages

# Update package lists
sudo apt-get -y update

# Install nginx
sudo apt-get -y install nginx

# Create a backup of the default configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
if [ -d "/var/www" ]; then
    sudo chown -R "$USER":"$USER" /var/www
    sudo chmod -R 755 /var/www
else
    sudo mkdir -p /var/www
    sudo chown -R "$USER":"$USER" /var/www
    sudo chmod -R 755 /var/www
fi

# create directories if not present
for dir in /var/www/{html,error}; do
    if ! [ -d "$dir" ]; then
        sudo mkdir -p "$dir"
    fi
done

# Echo "Hello World!" to the default index file
echo "Hello World!" | sudo tee "/var/www/html/index.nginx-debian.html"

# Define website directory
WEBSITE_DIR="/var/www/html"

# Restore default configuration for a 301 redirect
sudo sed -i '/server_name _;/a\    location = \/redirect_me {\n        return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default

# create new error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Restore default error page configurations
sudo sed -i '/error_page 404/c\    error_page 404 /404.html;' /etc/nginx/sites-available/default
sudo sed -i '/location \= \/404.html/c\    location = \/404.html {\n        root \/usr\/share\/nginx\/html;\n        internal;\n    }' /etc/nginx/sites-available/default

# Define server configuration
SERVER_CONFIG="server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root $WEBSITE_DIR;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    add_header X-Served-By \$hostname;
    location / {
        try_files \$uri \$uri/ =404;
    }
    location = /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}"

# Append server configuration to Nginx configuration file
echo "$SERVER_CONFIG" | sudo tee -a /etc/nginx/sites-available/default > /dev/null

# Restart Nginx service to apply changes
sudo service nginx restart

