#!/usr/bin/env bash 
# Script for transferring a file from our client to a server using SCP
# Assigning parameters to variables
# Check if correct number of arguments are provided

if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE SERVER_IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Transfer file using SCP
scp -o StrictHostKeyChecking=no -i "${ssh_key}" "${file_path}" "${username}"@"${server_ip}":~/
