#!/usr/bin/env bash 

# Function to display usage
usage() {
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}

# Check if number of arguments is less than 4
if [ "$#" -lt 4 ]; then
  usage
  exit 1
fi

# Assigning parameters to variables
file_path=$1
server_ip=$2
username=$3
ssh_key=$4

# Transfer file using SCP
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username"@"$server_ip":~/

# Check if SCP command was successful
if [ $? -eq 0 ]; then
  echo "File transfer successful!"
else
  echo "File transfer failed!"
fi

