#!/usr/bin/env bash
# Install nginx on web-01 server
# Nginx to listen on port 80

# Variables
nginx_web_root="/var/www/html"
custom_page_path="$nginx_web_root/index.html"
nginx_service="nginx"
hello_message="Hello World!"

# Update package list and install Nginx
sudo apt-get -y update
sudo apt-get -y install $nginx_service

# Create a custom HTML page with the string "Hello World!"
echo "$hello_message" | sudo tee $custom_page_path >/dev/null

# Modify Nginx configuration to serve the custom HTML file
sudo tee /etc/nginx/sites-available/default >/dev/null <<CONFIG
server {
    listen 80;
    server_name _;

    location / {
        root $nginx_web_root;
        index index.html;
    }
}
CONFIG

# Restart Nginx service
sudo service $nginx_service restart

