#!/usr/bin/env bash
# Configure URI permanent redirection

sudo apt-get -y update

sudo apt-get -y install nginx

echo "Hello World!" | sudo tee "/var/www/html/index.nginx-debian.html"

file="/etc/nginx/sites-available/default"

new_string="server_name _;\n\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"

sudo sed -i "s/server_name _;/$new_string/" $file

sudo service nginx start
