#!/usr/bin/env bash
# Configures Nginx server for redirection and default error pages

# Update package lists
sudo apt-get -y update

# Install nginx
sudo apt-get -y install nginx

# Create a backup of the default configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup

# Add "Hello World" message
sudo bash -c 'echo "Hello World" > /var/www/html/index.html'

# Restore default configuration for a permanent 301 redirect
sudo sed -i '/server_name _;/a\    location = \/redirect_me {\n        return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default

# Restart Nginx service to apply changes
sudo service nginx restart
