#!/usr/bin/env bash
# Configures Nginx server for redirection

# Update package lists
sudo apt-get -y update

# Install nginx
sudo apt-get -y install nginx

# Create a backup of the default configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup

# Replace the line with multiple lines using sed
new_string="server_name _;\n\n\trewrite ^\/redirect_me https:\/\/github.com permanent;"

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-available/default

sudo service nginx start
