#!/usr/bin/env bash
# Configures Nginx server for redirection and custom 404 page

# Update package lists
sudo apt-get -y update

# Install nginx
sudo apt-get -y install nginx

# Create a backup of the default configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup

# Add redirection rule to the Nginx configuration
sudo sed -i 's/server_name _;/&\n\trewrite \/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;/' /etc/nginx/sites-available/default

# Add custom 404 page configuration to Nginx
sudo bash -c 'cat > /etc/nginx/sites-available/custom_404' << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
        root /var/www/html;
        echo "<h1>404 Not Found</h1><p>Ceci n'est pas une page</p>";
    }
}
EOF

# Enable the custom 404 page configuration
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Test Nginx configuration
sudo nginx -t

# Reload Nginx to apply changes
sudo service nginx reload

# Start Nginx service if not already started
sudo service nginx start

