#!/usr/bin/env bash
# a Bash script that pings an IP address passed as an argument.

# Check if an argument is provided
if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Get the IP address from the command line argument
ip_address=$1

# Ping the IP address 5 times
ping -c 5 $ip_address
