#!/usr/bin/env bash
# Bash script to display FizzBuzz for multiples of 3 and 5, Fizz for multiples of 3, Buzz for multiples of 5, and the number otherwise

for ((i=1; i<=100; i++)); do
    # Check conditions for Fizz, Buzz, FizzBuzz, or the number itself
    if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]; then
        echo "FizzBuzz"
    elif [ $((i % 3)) -eq 0 ]; then
        echo "Fizz"
    elif [ $((i % 5)) -eq 0 ]; then
        echo "Buzz"
    else
        echo $i
    fi
done
