#!/usr/bin/env bash
# Bash script to display numbers from 1 to 20 with specific messages on certain iterations using a while loop and a case statement

counter=1

while [ $counter -le 20 ]; do
    # Use a case statement to check different conditions for each iteration
    case $counter in
        4)
            echo -e "$counter\nbad luck from China"
            ;;
        9)
            echo -e "$counter\nbad luck from Japan"
            ;;
        17)
            echo -e "$counter\nbad luck from Italy"
            ;;
        *)
            echo $counter
            ;;
    esac
    
    ((counter++))
done
